version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"  # Map Apache's port 80 to the host machine's port 9000
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    volumes:
      - .:/var/www/html  # Mount your Laravel application code into the container
    networks:
      - my_network  # Connect to the same network as php-apache

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network  # Connect to the same network as php-apache

volumes:
  mongo-data:

networks:
  my_network:
    driver: bridge
